### ISSUE TITLE
NPE  org.ice4j.stack.NetAccessManage

### ISSUE THREAD

**Issue by Nemo-G** [Nemo-G/jitsi-jvb#1]
``` Add peer CandidatePair with new reflexive address to checkList: CandidatePair (State=Frozen Priority=7962116751041232895):
        LocalCandidate=candidate:1 1 udp 2130706431 172.17.0.2 10000 typ host
        RemoteCandidate=candidate:10000 1 udp 1853824767 103.206.188.188 15155 typ prflx
Feb 10, 2021 9:32:29 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Add peer CandidatePair with new reflexive address to checkList: CandidatePair (State=Frozen Priority=7961835276064522239):
        LocalCandidate=candidate:1 1 udp 2130706431 172.17.0.2 10000 typ host
        RemoteCandidate=candidate:10001 1 udp 1853759231 101.87.245.214 10610 typ prflx
Feb 10, 2021 9:32:29 AM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Returning a candidate matching the address, while no candidates match both address (35.194.204.93:10000/udp) and base (candidate:1 1 udp 2130706431 172.17.0.2 10000 typ host): candidate:3 1 udp 1677724415 35.194.204.93 10000 typ srflx raddr 172.18.0.4 rport 10000 with base candidate:2 1 udp 2130706431 172.18.0.4 10000 typ host
Feb 10, 2021 9:32:29 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair succeeded: 172.17.0.2:10000/udp/host -> 103.206.188.188:15155/udp/prflx (stream-09643342b0400000.RTP).
Feb 10, 2021 9:32:29 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Adding allowed address: 103.206.188.188:15155/udp
Feb 10, 2021 9:32:29 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair validated: 35.194.204.93:10000/udp/srflx -> 103.206.188.188:15155/udp/prflx (stream-09643342b0400000.RTP).
Feb 10, 2021 9:32:29 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: Nominate (first valid): 35.194.204.93:10000/udp/srflx -> 103.206.188.188:15155/udp/prflx (stream-09643342b0400000.RTP).
Feb 10, 2021 9:32:29 AM org.jitsi.utils.logging2.LoggerImpl log
INFO: verify if nominated pair answer again
Feb 10, 2021 9:32:29 AM org.ice4j.stack.NetAccessManager handleFatalError
SEVERE: Unexpected Error!
java.lang.NullPointerException
        at org.ice4j.socket.MergingDatagramSocket.initializeActive(MergingDatagramSocket.java:577)
        at org.ice4j.ice.ComponentSocket.propertyChange(ComponentSocket.java:176)
        at org.ice4j.ice.IceMediaStream.firePairPropertyChange(IceMediaStream.java:877)
        at org.ice4j.ice.CandidatePair.nominate(CandidatePair.java:629)
        at org.ice4j.ice.Agent.nominate(Agent.java:1788)
        at org.ice4j.ice.DefaultNominator.strategyNominateFirstValid(DefaultNominator.java:144)
        at org.ice4j.ice.DefaultNominator.propertyChange(DefaultNominator.java:120)
        at org.ice4j.ice.IceMediaStream.firePairPropertyChange(IceMediaStream.java:877)
        at org.ice4j.ice.CandidatePair.validate(CandidatePair.java:667)
        at org.ice4j.ice.IceMediaStream.addToValidList(IceMediaStream.java:675)
        at org.ice4j.ice.Agent.validatePair(Agent.java:1752)
        at org.ice4j.ice.ConnectivityCheckClient.processSuccessResponse(ConnectivityCheckClient.java:641)
        at org.ice4j.ice.ConnectivityCheckClient.processResponse(ConnectivityCheckClient.java:405)
        at org.ice4j.stack.StunClientTransaction.handleResponse(StunClientTransaction.java:314)
        at org.ice4j.stack.StunStack.handleMessageEvent(StunStack.java:1040)
        at org.ice4j.stack.MessageProcessingTask.run(MessageProcessingTask.java:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

Feb 10, 2021 9:32:30 AM org.jitsi.utils.logging2.LoggerImpl log
WARNING: Returning a candidate matching the address, while no candidates match both address (35.194.204.93:10000/udp) and base (candidate:1 1 udp 2130706431 172.17.0.2 10000 typ host): candidate:3 1 udp 1677724415 35.194.204.93 10000 typ srflx raddr 172.18.0.4 rport 10000 with base candidate:2 1 udp 2130706431 172.18.0.4 10000 typ ho```

**Comment by Nemo-G** [comment]
Refer to this https://github.com/jitsi/ice4j/issues/205

1.  STUN config doesn't matter
2.  Need to make sure `.ENV.LOCAL_ADDRESS` not using jisi.meet defined docker network.

**Comment by Nemo-G** [comment]
The solution is that I modified `docker-compose.yml`, removing jitsi.meet network and make all containers use default `bridge` network.
